sudo: required
services:
  - docker
language: go
go:
  - '1.8'
before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - mkdir -p $GOPATH/bin
install:
  - make deps
script:
  - make test
before_deploy:
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 make
  - make cross-build
  - make dist
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: 'dist/*.{tar.gz,zip}'
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: make ci-docker-release
    on:
      # branch: master
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: DOCKER_IMAGE_TAG=$TRAVIS_TAG make ci-docker-release
    on:
      tags: true
